const sampleJobs = [
    {
        title: "Software Engineer",
        company: "TechCorp",
        location: "San Francisco, CA",
        salary: 120000,
        description: "Develop and maintain web applications.",
        requirements: ["JavaScript", "Node.js", "React"],
        jobType: "Full-time",
    },
    {
        title: "Data Analyst",
        company: "DataWorks",
        location: "New York, NY",
        salary: 85000,
        description: "Analyze and interpret complex data sets.",
        requirements: ["SQL", "Python", "Excel"],
        jobType: "Full-time",
    },
    {
        title: "Graphic Designer",
        company: "Creative Studio",
        location: "Los Angeles, CA",
        salary: 60000,
        description: "Design marketing materials and branding assets.",
        requirements: ["Photoshop", "Illustrator", "Creativity"],
        jobType: "Contract",
    },
    {
        title: "Marketing Manager",
        company: "Brandify",
        location: "Chicago, IL",
        salary: 95000,
        description: "Lead marketing campaigns and strategies.",
        requirements: ["SEO", "Content Marketing", "Leadership"],
        jobType: "Full-time",
    },
    {
        title: "Product Manager",
        company: "InnovateTech",
        location: "Austin, TX",
        salary: 110000,
        description: "Oversee product development lifecycle.",
        requirements: ["Agile", "Scrum", "Communication"],
        jobType: "Full-time",
    },
    {
        title: "Customer Support Specialist",
        company: "HelpDesk Inc.",
        location: "Remote",
        salary: 45000,
        description: "Provide customer support via email and chat.",
        requirements: ["Communication", "Problem-solving", "Empathy"],
        jobType: "Part-time",
    },
    {
        title: "DevOps Engineer",
        company: "CloudOps",
        location: "Seattle, WA",
        salary: 130000,
        description: "Manage cloud infrastructure and CI/CD pipelines.",
        requirements: ["AWS", "Docker", "Kubernetes"],
        jobType: "Full-time",
    },
    {
        title: "Content Writer",
        company: "WriteNow",
        location: "Remote",
        salary: 50000,
        description: "Create engaging content for blogs and websites.",
        requirements: ["Writing", "SEO", "Research"],
        jobType: "Contract",
    },
    {
        title: "HR Specialist",
        company: "PeopleFirst",
        location: "Boston, MA",
        salary: 70000,
        description: "Manage recruitment and employee relations.",
        requirements: ["HR Policies", "Recruitment", "Interpersonal Skills"],
        jobType: "Full-time",
    },
    {
        title: "Mobile App Developer",
        company: "Appify",
        location: "San Diego, CA",
        salary: 115000,
        description: "Develop mobile applications for iOS and Android.",
        requirements: ["Swift", "Kotlin", "UI/UX Design"],
        jobType: "Full-time",
    },
    {
        title: "Cybersecurity Analyst",
        company: "SecureNet",
        location: "Washington, DC",
        salary: 105000,
        description: "Monitor and secure IT systems against threats.",
        requirements: ["Cybersecurity", "Firewalls", "Incident Response"],
        jobType: "Full-time",
    },
    {
        title: "UI/UX Designer",
        company: "DesignPro",
        location: "Portland, OR",
        salary: 80000,
        description: "Design user interfaces and improve user experiences.",
        requirements: ["Figma", "Wireframing", "Prototyping"],
        jobType: "Full-time",
    },
    {
        title: "Sales Executive",
        company: "SalesForce",
        location: "Dallas, TX",
        salary: 75000,
        description: "Drive sales and build client relationships.",
        requirements: ["Sales", "Negotiation", "CRM"],
        jobType: "Full-time",
    },
    {
        title: "AI Researcher",
        company: "AI Labs",
        location: "Palo Alto, CA",
        salary: 140000,
        description: "Research and develop AI models and algorithms.",
        requirements: ["Machine Learning", "Python", "TensorFlow"],
        jobType: "Full-time",
    },
    {
        title: "Accountant",
        company: "FinancePro",
        location: "Atlanta, GA",
        salary: 65000,
        description: "Manage financial records and prepare reports.",
        requirements: ["Accounting", "Excel", "Attention to Detail"],
        jobType: "Full-time",
    },
    {
        title: "Backend Developer",
        company: "CodeBase",
        location: "Denver, CO",
        salary: 125000,
        description: "Develop and maintain server-side applications.",
        requirements: ["Node.js", "Express", "MongoDB"],
        jobType: "Full-time",
    },
    {
        title: "Social Media Manager",
        company: "SocialBuzz",
        location: "Miami, FL",
        salary: 55000,
        description: "Manage and grow social media presence.",
        requirements: ["Social Media", "Content Creation", "Analytics"],
        jobType: "Part-time",
    },
    {
        title: "Electrical Engineer",
        company: "PowerGrid",
        location: "Houston, TX",
        salary: 95000,
        description: "Design and maintain electrical systems.",
        requirements: ["Electrical Engineering", "AutoCAD", "Problem-solving"],
        jobType: "Full-time",
    },
    {
        title: "Business Analyst",
        company: "BizSolutions",
        location: "Phoenix, AZ",
        salary: 90000,
        description: "Analyze business processes and recommend improvements.",
        requirements: ["Business Analysis", "Data Analysis", "Communication"],
        jobType: "Full-time",
    },
    {
        title: "Intern - Software Development",
        company: "Startup Inc.",
        location: "Remote",
        salary: null,
        description: "Assist in software development projects.",
        requirements: ["Programming Basics", "Eagerness to Learn"],
        jobType: "Internship",
    },
];

module.exports = {sampleJobs:sampleJobs};